/**
 * Media pipeline.
 *
 * Source renders from Chaabi are 4000-7000px and up to 15 MB each. Shipping those
 * to next/image as-is means the optimizer decodes a 15 MB JPEG on every cache miss,
 * which is slow enough to matter. So we do the expensive resize once, at build time,
 * and hand next/image a sane 2560px master. It still emits AVIF/WebP responsive
 * variants from there.
 *
 * We also emit a 20px LQIP per image as a base64 data URI, plus intrinsic dimensions,
 * into a generated TypeScript manifest. Components import that manifest, so every
 * <Image> in the codebase gets correct width/height (no CLS) and a real blur
 * placeholder without anyone hand-maintaining numbers.
 *
 *   npm run media:prep
 */
import { readdir, mkdir, writeFile } from "node:fs/promises";
import { join, parse } from "node:path";
import sharp from "sharp";

const SRC = "assets-src";
const OUT = "public/media";
const MANIFEST = "src/data/media.generated.ts";

const MASTER_WIDTH = 2560;
const LQIP_WIDTH = 20;

async function main() {
  await mkdir(OUT, { recursive: true });
  const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png)$/i.test(f));

  const entries = [];
  for (const file of files.sort()) {
    const { name } = parse(file);
    const input = sharp(join(SRC, file), { limitInputPixels: false });
    const meta = await input.metadata();

    const targetWidth = Math.min(MASTER_WIDTH, meta.width ?? MASTER_WIDTH);
    const scale = targetWidth / (meta.width ?? targetWidth);
    const targetHeight = Math.round((meta.height ?? 0) * scale);

    await input
      .clone()
      .resize(targetWidth, null, { withoutEnlargement: true })
      .jpeg({ quality: 82, mozjpeg: true, chromaSubsampling: "4:4:4" })
      .toFile(join(OUT, `${name}.jpg`));

    // LQIP: deliberately tiny. Blurred up by the browser, it costs ~600 bytes
    // inline and removes the grey-box flash on slow connections.
    const lqip = await sharp(join(SRC, file), { limitInputPixels: false })
      .resize(LQIP_WIDTH)
      .webp({ quality: 30 })
      .toBuffer();

    entries.push({
      key: name,
      src: `/media/${name}.jpg`,
      width: targetWidth,
      height: targetHeight,
      blur: `data:image/webp;base64,${lqip.toString("base64")}`,
    });

    console.log(
      `${name}  ${meta.width}x${meta.height} -> ${targetWidth}x${targetHeight}`,
    );
  }

  const body = entries
    .map(
      (e) =>
        `  "${e.key}": {\n` +
        `    src: "${e.src}",\n` +
        `    width: ${e.width},\n` +
        `    height: ${e.height},\n` +
        `    blur: "${e.blur}",\n` +
        `  },`,
    )
    .join("\n");

  await mkdir("src/data", { recursive: true });
  await writeFile(
    MANIFEST,
    `// GENERATED by scripts/prepare-media.mjs — do not edit by hand.\n` +
      `// Run \`npm run media:prep\` after adding files to assets-src/.\n\n` +
      `export type MediaAsset = {\n` +
      `  src: string;\n` +
      `  width: number;\n` +
      `  height: number;\n` +
      `  blur: string;\n` +
      `};\n\n` +
      `export const media = {\n${body}\n} as const satisfies Record<string, MediaAsset>;\n\n` +
      `export type MediaKey = keyof typeof media;\n`,
    "utf8",
  );

  console.log(`\n${entries.length} assets -> ${MANIFEST}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
