/**
 * Media pipeline.
 *
 * Source renders from Chaabi are 4000-7000px and up to 15 MB each. Shipping those
 * to next/image as-is means the optimizer decodes a 15 MB JPEG on every cache miss,
 * which is slow enough to matter. So we do the expensive resize once, at build time,
 * and hand next/image a sane master. It still emits AVIF/WebP responsive variants
 * from there.
 *
 * We also emit a 20px LQIP per image as a base64 data URI, plus intrinsic dimensions,
 * into generated TypeScript manifests. Components import those manifests, so every
 * <Image> gets correct width/height (no CLS) and a real blur placeholder without
 * anyone hand-maintaining numbers.
 *
 * TWO manifests, on purpose:
 *
 *   media.generated.ts          everything not prefixed `g_` — heroes, posters, the
 *                               images client components need. Imported by `Figure`,
 *                               which client components also use, so this one ships
 *                               to the browser and must stay small.
 *   media.gallery.generated.ts  `g_*` files — programme gallery images. Imported only
 *                               by the server-rendered `GalleryFigure`, so ~150 extra
 *                               entries and their LQIPs never reach a client bundle.
 *
 * Incremental: a master is re-encoded only when its source is newer.
 *
 *   npm run media:prep
 */
import { readdir, mkdir, writeFile, stat } from "node:fs/promises";
import { join, parse } from "node:path";
import sharp from "sharp";

const SRC = "assets-src";
const OUT = "public/media";
const MANIFEST = "src/data/media.generated.ts";
const GALLERY_MANIFEST = "src/data/media.gallery.generated.ts";

const MASTER_WIDTH = 2560;
/** Gallery images are shown at most full-viewport in a lightbox. */
const GALLERY_WIDTH = 2200;
const LQIP_WIDTH = 20;

const isGallery = (name) => name.startsWith("g_");

async function newer(src, out) {
  try {
    const [a, b] = await Promise.all([stat(src), stat(out)]);
    return a.mtimeMs > b.mtimeMs;
  } catch {
    return true;
  }
}

function manifest(entries, constName, typeName, header) {
  const body = entries
    .map(
      (e) =>
        `  "${e.key}": {\n` +
        `    src: "${e.src}",\n` +
        `    width: ${e.width},\n` +
        `    height: ${e.height},\n` +
        `    blur: "${e.blur}",\n` +
        `  },`,
    )
    .join("\n");
  return (
    `// GENERATED by scripts/prepare-media.mjs — do not edit by hand.\n` +
    `// Run \`npm run media:prep\` after adding files to assets-src/.\n` +
    header +
    `\nexport type MediaAsset = {\n  src: string;\n  width: number;\n  height: number;\n  blur: string;\n};\n\n` +
    `export const ${constName} = {\n${body}\n} as const satisfies Record<string, MediaAsset>;\n\n` +
    `export type ${typeName} = keyof typeof ${constName};\n`
  );
}

async function main() {
  await mkdir(OUT, { recursive: true });
  const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png)$/i.test(f));

  const core = [];
  const gallery = [];
  let encoded = 0;
  for (const file of files.sort()) {
    const { name } = parse(file);
    const src = join(SRC, file);
    const out = join(OUT, `${name}.jpg`);
    const max = isGallery(name) ? GALLERY_WIDTH : MASTER_WIDTH;

    if (await newer(src, out)) {
      await sharp(src, { limitInputPixels: false })
        .rotate()
        .resize(max, null, { withoutEnlargement: true })
        .jpeg({ quality: isGallery(name) ? 80 : 82, mozjpeg: true, chromaSubsampling: "4:4:4" })
        .toFile(out);
      encoded++;
      console.log(`${name}  -> encoded`);
    }

    // Dimensions and LQIP come from the master: identical result, a fraction of
    // the decode cost of a 7000px original.
    const meta = await sharp(out).metadata();
    // LQIP: deliberately tiny. Blurred up by the browser, it costs a few hundred
    // bytes inline and removes the grey-box flash on slow connections.
    const lqip = await sharp(out).resize(LQIP_WIDTH).webp({ quality: 30 }).toBuffer();

    (isGallery(name) ? gallery : core).push({
      key: name,
      src: `/media/${name}.jpg`,
      width: meta.width,
      height: meta.height,
      blur: `data:image/webp;base64,${lqip.toString("base64")}`,
    });
  }

  await mkdir("src/data", { recursive: true });
  await writeFile(MANIFEST, manifest(core, "media", "MediaKey", ""), "utf8");
  await writeFile(
    GALLERY_MANIFEST,
    manifest(
      gallery,
      "galleryMedia",
      "GalleryKey",
      `// Server-only by convention: import it only from GalleryFigure, never from a\n// client component, or ~150 LQIPs ship to the browser.\n`,
    ),
    "utf8",
  );

  console.log(`\n${encoded} encoded · ${core.length} core -> ${MANIFEST} · ${gallery.length} gallery -> ${GALLERY_MANIFEST}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
