// GENERATED by scripts/prepare-media.mjs — do not edit by hand.
// Run `npm run media:prep` after adding files to assets-src/.

export type MediaAsset = {
  src: string;
  width: number;
  height: number;
  blur: string;
};

export const media = {
  "aerial_resort": {
    src: "/media/aerial_resort.jpg",
    width: 654,
    height: 492,
    blur: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBACdASoUAA8APxFysFAsJqSisAgBgCIJZQDG9CHYfeb5Ty8RCg2EAAD+PkukkH7MOMEx8S6zXdECC47if2VeYUM/wdzMHxohPK7dxD97t+/cIJB3W0TnEwjmwH4J85AxYhl9hoAAAA==",
  },
  "facade_street": {
    src: "/media/facade_street.jpg",
    width: 282,
    height: 178,
    blur: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoUAA0APxFwsFAsJiSisAgBgCIJZQC7ABI9ciCjcmBIqAD+xuK49Apd0xGXGSlQuhocb+/3wRz7x8irlYxT7Oc33W4zYpcvZq7muBXW+S31fr9wdQGkaOzC+11+Pd14OigAAA==",
  },
  "hero_courtyard": {
    src: "/media/hero_courtyard.jpg",
    width: 1672,
    height: 941,
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQBACdASoUAAsAPxFysFAsJqSisAgBgCIJZACdMoKP/bf4DaAqwqRH37pldCAA9gHPxMdcvzYig7CAbj60MGatkZnRdsGMgYPa2PxYEOC7rJ1BUWARsyy+AfqWmVyaAAA=",
  },
  "lobby_terrazzo": {
    src: "/media/lobby_terrazzo.jpg",
    width: 730,
    height: 510,
    blur: "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBACdASoUAA4APxFwsFAsJiSisAgBgCIJYgCdMoACiBknqYBE1fCCUADNmfoiXmPFe2k/bRabbP1tbwTxm1TQxR0gzQcThVrQtM6uJ7Vr7W3dCEMVa0Di0riNKB/jgZf8SBHONtr4jq0+D5o/NqG5/dtRlO0V0mqhFFXMKx0l00uAAAA=",
  },
  "maquette_model": {
    src: "/media/maquette_model.jpg",
    width: 515,
    height: 388,
    blur: "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACwAwCdASoUAA8APxFwsFAsJiSisAgBgCIJZQC7ACHC8axIUcKiAAD+qh2Onr87PzXX+HBsOlHlx7+7lKdnTFPlFNYJybgcopIikmfk++O/HPzZeH8Cc+ber6fuJJa/cwulUoujL6BfauJB53DTE+WrPKIaWGx7ujCwR7bx94r+DEOoAAA=",
  },
  "rg1_DSC00924": {
    src: "/media/rg1_DSC00924.jpg",
    width: 2560,
    height: 1710,
    blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQBACdASoUAA0APxFysVAsJqSisAgBgCIJZgCsIHGJ/gNrpVnQsZAh0AD9jhA6c2dcuTauMoTRuvYPSOHmNHCA2Ss08DiG80O+wdVY0Oe74h1b06tTSK49zEI5dySh5eHRN4TcKdbcHsUaEPc3ZT4CgAA=",
  },
  "rg1_DSC08344": {
    src: "/media/rg1_DSC08344.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJZQDE2CHgGQSTgyyq8IogAP6MPaJdRsbC0Zrt2F81NFx9Jo/3vsezwuOpmnR322gtNKLPH6+RD9yTRoKehN/5fAA=",
  },
  "rg1_DSC08442": {
    src: "/media/rg1_DSC08442.jpg",
    width: 2560,
    height: 1814,
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAwCdASoUAA4APxFwsFAsJiSisAgBgCIJYwCsACB6FsHm2KgA/ovn8no8VWCy9gWNYlYyg2SyhIY241xO5ZTyB5j+3rVbAOvZp35snGdsaMQNAgCA0v25WFs4ugAA",
  },
  "rg1_DSC08446": {
    src: "/media/rg1_DSC08446.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJYgC7ABoivzbZ2Kf9yDFAAP6wr13pGaqOpH5LOed4sq/CtEw1LtN1H5FNip1pniqMJLY8lwH4nORRrKj8K7l3GQAAAA==",
  },
  "rg1_DSC08548": {
    src: "/media/rg1_DSC08548.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJQBdkGQBTMMYB8FErMJQAAM4VWObn6CZuzMbotUKG8OqjgBdxk6AAMQl3Wf63+OLClghKoT6Kk8KOgP/eGt8qi8l2Hbr9D2GoRF6I9axh4d8tDMOPU+AAAAA=",
  },
  "rg1_DSC08579": {
    src: "/media/rg1_DSC08579.jpg",
    width: 2560,
    height: 1786,
    blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoUAA4APxFysFAsJqSisAgBgCIJagCdABssn56ct5QKFgYAAP7DZ4LfSqX7c+BAC26MFojNu5cei5q55hZChSrlTY2GymHop7z6lkF1dfrMLCNmYmTcSFJbeUem2uH9Z9TUGS0So/pAAA==",
  },
  "rg1_DSC08588": {
    src: "/media/rg1_DSC08588.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwAwCdASoUAA0APxFysFAsJqSisAgBgCIJZACdABVL0UQTdaOVoAD8hxX8ynAGuRtWtijQ2TKNV9iYvzO6pW5Jj+PrzxzPmmQWgI5JsZ8fvWjZjz8XG4W86bRBI49fDDUJYUKWTT/ksihh0YQFoOtDq4AAAA==",
  },
  "rg1_DSC08601": {
    src: "/media/rg1_DSC08601.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoUAA0APxFwsFAsJiSisAgBgCIJQBYdhCqhXL6bV6ftk3tAAPzpzP8FFJaMqClgLgxD/8QxwAEcakkEfygR3xD4ZwOyQbRtMRmd3oLSnMG2CjXkbnyAgNXKqwX4V7EXyxeAAA==",
  },
  "rg1_DSC08632": {
    src: "/media/rg1_DSC08632.jpg",
    width: 2560,
    height: 1437,
    blur: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQBACdASoUAAsAPxFysFAsJqSisAgBgCIJbACdL11s/7sAAksWpuyXhtZAAPn1Fo9AVsosyhFz8OMrHixPwGM1n0PzDInuB7KckRIG+pa1Ucn6sU1arywL4//yi98Ur+MO4f//hBMAAA==",
  },
  "rg2_Chambre_Enfants": {
    src: "/media/rg2_Chambre_Enfants.jpg",
    width: 2560,
    height: 1600,
    blur: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoUAAwAPxFysFAsJqSisAgBgCIJYwC06BmXqZFl4krn/AAA932pIQAbUJ6myBD424aD/qYr0OfrmbH+y+H+7crqz5euSEWYbbZZOhB8tc9dy+Nts/s1f4i2bNS4MAAA",
  },
  "rg2_Chambre_Parentale_": {
    src: "/media/rg2_Chambre_Parentale_.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJZQC+SBjZ/lkR6+nZuNGAAP5oH1YN0LY6PWCHqFRsEbrQVVgr+ux4PA4Rx2JKQnm7OZ8NE0owr88iyi74KQrJNdF7PPyJk/Xp/JhawZgLOHTa0itdAAAA",
  },
  "rg2_Cuisine_v2": {
    src: "/media/rg2_Cuisine_v2.jpg",
    width: 2560,
    height: 3012,
    blur: "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBQCdASoUABgAPxF8slSsJ6QjKAqpgCIJZQDGfBEz3n/BUnweJqAErCqUTqvAmdu0rQAA/rSIkOXP+F38+pTnbQMgcX/kkmCMYF22CUmO3A6WpXqabt+Gv+q/REY+YG5AVyLyer3ingS5XtEq8FoO+yrAhDEhNoHXbkqTgnKNs2cw2F+vtu8oCA/Fel4A",
  },
  "rg2_Ext_Cam_A1_Commerce_1": {
    src: "/media/rg2_Ext_Cam_A1_Commerce_1.jpg",
    width: 2560,
    height: 1600,
    blur: "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwAwCdASoUAAwAPxFysFAsJqSisAgBgCIJYwAAPFWOCAlElZsHAAD33c4fffqJydhLsSkEC4gDqbWqrduMp0CPsyVhghTdNudPvq6DTp6XqctooIUkPuAJXkjl7TRtgfS+avaLsUiJ/q+/bNWvN+N2/MwAAA==",
  },
  "rg2_Ext_Cam_c1_jardin_1": {
    src: "/media/rg2_Ext_Cam_c1_jardin_1.jpg",
    width: 2560,
    height: 1623,
    blur: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQAwCdASoUAA0APxFysFAsJqSisAgBgCIJQBOgBF8V9m1Su6IWkAAA9ijAp5a5/o+j7eepxk0lk7jjgZ+a19YTm9U0qLrmJ73xGr+h7xoAIMD+cJF27/r491z59nf3lDbNnaHyWOoRo/yzzC5nE78VWu732QigAAA=",
  },
  "rg2_SDB_V2": {
    src: "/media/rg2_SDB_V2.jpg",
    width: 2560,
    height: 3012,
    blur: "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBQCdASoUABgAPxF6tFQsJ6SjKAqpgCIJZQC84A9Lv39WF5/AHobAXzWPVP79iDIAAP35qa4osji4yFgZqqRerq+mfx/91BXcyLsDHtA36L0fGI5T13vCOa39qf7tSbJvGKKY+vSrrkQzpapoTaPHK2JpDxUKvp7q7QjxNP4shHMbxgAAAA==",
  },
  "rg2_Sejour_v2": {
    src: "/media/rg2_Sejour_v2.jpg",
    width: 2560,
    height: 1536,
    blur: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoUAAwAPxFysFAsJqSisAgBgCIJZwAAWqAN/x0+uTMoggJgAP7TzQc+r1qxBexpVE8my5DEGf+VF9QqwkDsfO5RCFRHYY5VE/98ruyXeGfG6ix9j3kuAA==",
  },
  "rg2_TypeB_3": {
    src: "/media/rg2_TypeB_3.jpg",
    width: 2560,
    height: 1600,
    blur: "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBACdASoUAAwAPxFysFAsJqSisAgBgCIJYgCdMoACfMfjMmeJKcWfAAAA/mksjqjyZvZQxuToyzOMmjsRrifsFCBfsVnlE6jYiojP2niDnzvbSUMBYvylJRXF3+16vRa703U3To/33dsowCZoN/xtIopSWQnLH4EsijgA",
  },
  "st_courtyard_arches": {
    src: "/media/st_courtyard_arches.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoUAA0APxFysVAsJqSisAgBgCIJQBgbg+TqbEmrzcAA/vDfFBHjJgU2sNJiXZej1IEXCqysuksRv4bVTuKbYkugc4AAAA==",
  },
  "st_courtyard_screens": {
    src: "/media/st_courtyard_screens.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABwAwCdASoUAA0APxFysFAsJqSisAgBgCIJZQCdABaEpaAN1AAA/tBR6WYF6aPwm6VyJScA+pPIT+vW/0bSHf9Eqab7oG//+oECsAOoW65y+AAA",
  },
  "st_facade_beige": {
    src: "/media/st_facade_beige.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQBACdASoUAA0APxFysFAsJqSisAgBgCIJZgCdMoRisAtAFf0g674pVMAAAP02FVbvyUM49+bbXXSBfBno8VOiavb9UnftsFU17+81pKbONUHT7BauOjdKE8bv5pmY9jJaEFP05wF2AAAA",
  },
  "st_marrakech_koutoubia": {
    src: "/media/st_marrakech_koutoubia.jpg",
    width: 2560,
    height: 1920,
    blur: "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoUAA8APxFwsFAsJiSisAgBgCIJQBdgBAxX3nv6zFqrIt0ocAD8soOUm1B4E3l8e46qJqn6gO91P7JTu0P1P5V4hr1mmWamXNhONCWnc3i6hjJpCn5cVjBzLp4lfqaxdTbNvKifJcvuhEEbdhVLs+YcUCxDGFHgRcSueN1UMA09UBwk6wAAAA==",
  },
  "st_salon_warm": {
    src: "/media/st_salon_warm.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJYwCdABKjs9fB0YMu9q0AAP6XmHttZmbI858wXo+VwovZ0bxiQom7TC/h3bVwby7FmHUUZM5sPN5/fEjGw/P9IJr1HH09RKHQ5IuLHXF+AA==",
  },
  "st_terrace_view": {
    src: "/media/st_terrace_view.jpg",
    width: 2560,
    height: 1920,
    blur: "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoUAA8APxFysFAsJqSisAgBgCIJYgCdAB5fxbxmvi6T50AUAADiWKv/I3g+y9JxcfNJa1Jdx+wZoDr/mMec30pV0GcEb3zzugzA11qoru9eiM1/wKNgxgQb+HyvFibR71QVcfX7uSCKUdXdNsfveSJPvo8f0QAA",
  },
  "st_villa_pool_dusk": {
    src: "/media/st_villa_pool_dusk.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJZgCdIMgCKrG9PUjEG6hCAP7pHPL+AScpRqF+YNBhoL24QvdGADsR4OnZ6RZYyxqswUrJ9v2N3nU+GUGK49Yk+GffCwWBKMN6niPay0OtjBmeHAAAAA==",
  },
  "th_amaia": {
    src: "/media/th_amaia.jpg",
    width: 2068,
    height: 1167,
    blur: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAwCdASoUAAsAPxFysVCsJqSisAgBgCIJZgCsLwAAkzBKHXSoNdgAAP3ixefCFgLlGbGm2IFH0pw/NMbh8j7dOBf/T/KNt0sVCF/kvShZEs7jy59QtaJxXsEGX0vBGoM+dQS++jf1JciM3krWAAAA",
  },
  "th_assalam_tg": {
    src: "/media/th_assalam_tg.jpg",
    width: 2560,
    height: 1440,
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoUAAsAPxFysVCsJqSisAgBgCIJZQDA3CGWOTlK+cUjB3gwAP6ykVNUZvC9rw4ZfPwJ0Re7hwUtceIxhMmmOqNiARSCdAdtCfyKFgyRQIjE5L4bFbNexogAAAA=",
  },
  "th_bougainvillier": {
    src: "/media/th_bougainvillier.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAwCdASoUAA0APxFysFAsJqSisAgBgCIJZQAu/8ArvOwzcKZLSAD9+bbRiWvpzZEeX6WNRmd5JJ1swCdLS7XdPDqo0HausrZe0ZFn1DHk3qDV42CyXo64NDUrQWa5v1QaiLZMCCA8X8KQQWwAAA==",
  },
  "th_dyar_al_bahia": {
    src: "/media/th_dyar_al_bahia.jpg",
    width: 1304,
    height: 904,
    blur: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASoUAA4APxFysFAsJqSisAgBgCIJaACdIDZBOqiIA0er1QAA3U458vLAhlF8HatxiYvu2A/Y8RRtuEUEqH4eEKvDCQzAxV2yMJd3qzpXyQWOcsJveWFT3pukMy4HfSQgB41VLAAA",
  },
  "th_izdihar": {
    src: "/media/th_izdihar.jpg",
    width: 2560,
    height: 1335,
    blur: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABwAwCdASoUAAoAPxFysFAsJqSisAgBgCIJQBibAqoxT1KXuigA3dbJV80KAxVL2irz4OspblJoru8sl05NyVwp1Si7/cSi+Ori7Ofo2YX86wu8uQhPmh8oAAA=",
  },
  "th_lots": {
    src: "/media/th_lots.jpg",
    width: 1274,
    height: 715,
    blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAwCdASoUAAsAPxFwsFAsJiSisAgBgCIJbACdACEjL2hXJxyA+AAA/lHAKGLNEQizoLZVm6uZct+8n2Mi4vNwiyOIvr+b5QEHY3JKY2iznUIKUMt4fte/vl5oZOuvz5U/3uZhTZPkpKbHIAA=",
  },
  "th_maamora": {
    src: "/media/th_maamora.jpg",
    width: 514,
    height: 293,
    blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoUAAsAPxFwsFAsJiSisAgBgCIJbACdACEjL5S73KiirZAAAP5RwChlAoExlDrqfZpdikDGyikWED0o3SMFmgj4yUi4BeVTCVdKeaQPkWn8mck2Yp3HPwdg+yhMfKBOvKqVmsLe0rHAAA==",
  },
  "th_oceane": {
    src: "/media/th_oceane.jpg",
    width: 2560,
    height: 1584,
    blur: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwAwCdASoUAAwAPxFysFAsJqSisAgBgCIJQBOgBFq/4YitNAIZKYhoAPjk77p7vxjr9BcnqGSP+lxmMhMtnZ1245zzzxBXvVd2ujFot6QHFLMU3x6R4H7YFHsaSGwhOwaZ58/54B80oVstsDOQPJd/8NroeJ5PEchO6fsojAA=",
  },
  "th_odyssee": {
    src: "/media/th_odyssee.jpg",
    width: 2560,
    height: 1620,
    blur: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQBACdASoUAA0APxFysFAsJqSisAgBgCIJZQC7ABnhx6kmRy29xO3bYAD+xuX0jOgUu3VL6SyPr2wp6vgjmpvpHUz0oT0kgCc5pTPmFC18c9FmHD+AoCr22+Udt+Pd129AAA==",
  },
  "th_odyssee_studios": {
    src: "/media/th_odyssee_studios.jpg",
    width: 1536,
    height: 1024,
    blur: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoUAA0APxFysFAsJqSisAgBgCIJYgCdIHACvc9l84Vkw8wA/fiRNmsXldjsLgOPuLl6HCxmsc+V2clM1zKIDtBEI//brIt2KpXLXStusO0ehHeokYdtZO4AoPuVSV0LxBLtZgnP7YEGSiZ2X1W+18AA",
  },
  "villas_pool_life": {
    src: "/media/villas_pool_life.jpg",
    width: 2000,
    height: 1238,
    blur: "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQAwCdASoUAAwAPxFysFAsJqSisAgBgCIJQBOgBFq/4dusbEob75QA+OTvunvA1RLDhfSa34wzvBuKo9BiZ3W/aNZ40Zu6JTaQ3gmDJIlHr2/X6nAVOE4U4HDLANH+96r59X6n9r8rZO0PhyIJiNBAnJcd1B0M3Fy4lgAA",
  },
  "villas_pool_wide": {
    src: "/media/villas_pool_wide.jpg",
    width: 2000,
    height: 1335,
    blur: "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoUAA0APxFysFAsJqSisAgBgCIJQBOmUABp9nDEf67hPLOBAAD+a508LTB+05uweIAbUkqOtCcvC7LcSNC2DRxlW5LuldvRcL7h15lav+uJZhMSivzi3Z8xwKFRXO8n9k3PiYy+T4k4FMdbzFRjrUJqVli8gAAA",
  },
} as const satisfies Record<string, MediaAsset>;

export type MediaKey = keyof typeof media;
