// GENERATED by scripts/prepare-media.mjs — do not edit by hand.
// Run `npm run media:prep` after adding files to assets-src/.

export type MediaAsset = {
  src: string;
  width: number;
  height: number;
  blur: string;
};

export const media = {
  "hp_al_anbar": {
    src: "/media/hp_al_anbar.jpg",
    width: 2560,
    height: 1440,
    blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoUAAsAPxFysFCsJqSisAgBgCIJQBfnBEQXy8fQ5izpVjMAAP7eu7nY7tTXhpm3+uoM1nmebDyZBUd6HCpuXUDdPR8Qr3jSIs4FbizFW6gWoBcNMm9VKIEMstYDSNmebOX4s6w8lAA=",
  },
  "hp_al_anbra": {
    src: "/media/hp_al_anbra.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoUAA0APxFysFAsJqSisAgBgCIJQBWAP4AJE2jv2pFfw0AA+W5SBDiLZi2rtCIzt/mlkb/+orAWXZHIvGFfQLjc9i2Zg/A3xeUdI7D772bmkOanN+58mc6mA85EIOa72qXfDnzT1rWwJZDAAAA=",
  },
  "hp_al_yassamine": {
    src: "/media/hp_al_yassamine.jpg",
    width: 2272,
    height: 1516,
    blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQBACdASoUAA0APxFysFAsJqSisAgBgCIJYwCw7CG/ZsdY0cm4RNfhAAD+3xV026S3Yth/rf9Du280eTpIrr6DBFE6bOal6zYmbIn6X3xhnzMlNOEwfFp+7ju8cfvDGz94Ki+G//xcCSaeBtAkg4+rkAA=",
  },
  "hp_assafa": {
    src: "/media/hp_assafa.jpg",
    width: 2560,
    height: 1920,
    blur: "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoUAA8APxFysFAsJqSisAgBgCIJZQC7ACB712mTCoct9p0AAPzw39W4bduZeVqQegBgZGC9Osi3wVoitazqj8a0SB7FV74Z7JoASVNz+Ofju3aZlbz21O82tKD2nF+DMkE43/iDMk1dqJqihE/AAA==",
  },
  "hp_jasmin": {
    src: "/media/hp_jasmin.jpg",
    width: 2560,
    height: 1440,
    blur: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoUAAsAPxFysFAsJqSisAgBgCIJYwCdABtsx+ddQAdqN4AA9V8tVUw/yn2gDhehK0Xtg2DFoE/vZbpKyPHgYwMREht663DKlY4dYz5qID0QpNTQduoZqxe0mN3jBjsAxZiqKijp8Rrz4AAA",
  },
  "hp_jnane_souss": {
    src: "/media/hp_jnane_souss.jpg",
    width: 2560,
    height: 1706,
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoUAA0APxFwsFAsJiSisAgBgCIJQBOgBC0P9bL5OivGAAD+sQHzXTsQUsEWbiGM9y60FWui/b9qyuivkN2JOMEHRtz6fYeBIrUF96rVS/sBb/2u4Wxd+AAA",
  },
  "hp_les_pins_de_maamora": {
    src: "/media/hp_les_pins_de_maamora.jpg",
    width: 2560,
    height: 1440,
    blur: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBACdASoUAAsAPxFwsFAsJiSisAgBgCIJaACdIE3J/gNpr9d1J99f/AD+zYMCyxgaitsL8AuZF32GAQEE1k/Xd7G8Yxlypy3j2eZdgVqRfhptz/D/WDhpdsM6u+cWlzDwZt0KlBs4AA==",
  },
  "hp_massylia": {
    src: "/media/hp_massylia.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoUAA0APxFysFAsJqSisAgBgCIJYwAAUpyYO7DlAohBOAD+sQFD4zSNrUcHaF9hTI5CPv0Cavxa/KFc3BGE7Xg1MqtZN9+dHssCuMJo4Ugondv35G7yXglgAAA=",
  },
  "hp_patio_verde": {
    src: "/media/hp_patio_verde.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoUAA0APxFysFAsJqSisAgBgCIJQBOgA9WhM0sltC62ggAA4SQyH3F5f/MLAlA3WMOtkl6aulBc+nW0VwDKLhe1rhwyr+DfqA1Eag7LD9+KSLbn4x2K4dBLwg+7eDnfgAA=",
  },
  "rg1_DSC00924": {
    src: "/media/rg1_DSC00924.jpg",
    width: 2560,
    height: 1710,
    blur: "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwBACdASoUAA0APxFysFAsJqSisAgBgCIJZgCsIF5J/gN6TdI5DhdRXwAA/Y4QOnNnx32O6soAUnJ9/OItYY5SPA61+kB8dsE1L2k1vFeOucaYtIMXcgD5ffnlsYXFihGN0bMvxthEejQCiRX4En1s3oAAAA==",
  },
  "rg1_DSC08344": {
    src: "/media/rg1_DSC08344.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAwCdASoUAA0APxF0sFCsJqSisAgBgCIJZQDE2CHe6l49kNqHeQAA/ow9ol2p5jQiDWbbUHnrCg7YuXstvVGwA0MW4XTHD0uYK+tt8CCaHrG0c7CkDF2mwAA=",
  },
  "rg1_DSC08442": {
    src: "/media/rg1_DSC08442.jpg",
    width: 2560,
    height: 1814,
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoUAA4APxFysFAsJqSisAgBgCIJYwCsACB6FsHnN9cAAP6NmjQBlZh92NFdFR6hqf3TwaBtyiEHpcHaIfD7zAT4kaoMwh3SCMF6WxNqy1GjeyeBaKU4HwAA",
  },
  "rg1_DSC08446": {
    src: "/media/rg1_DSC08446.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJYgC7ABoivwcJZH/F4aAAAP6wr13pGaqOpH5LOed4sq/CtEw14GygL6iPp3GiAKvrwn1W0bascpOEq/jwJLrsbcAAAA==",
  },
  "rg1_DSC08476": {
    src: "/media/rg1_DSC08476.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwBACdASoUAA0APxFysFAsJqSisAgBgCIJaACdMoM20E50eWXOrHt87zCD0AD+1v8OGRt1zIlFsATFvuRlGRNxoSdImXzxAewOxo1RYbF4OMRgvJiQaY13OcSc9v/yFf4afOQ9ScR+q0VIUW4ZhNCEwAA=",
  },
  "rg1_DSC08548": {
    src: "/media/rg1_DSC08548.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAwCdASoUAA0APxFysFCsJqSisAgBgCIJQBahFThTMMX/ManA2ADOFVjm5+gmbszG6LVChvDqo4AXcZOf71P3+wyMhOHntJQN45iGJN6Sm/aOoqAM1P8yxoGtNiZGJEa1KXGb+NaWW08FfYAAAA==",
  },
  "rg1_DSC08579": {
    src: "/media/rg1_DSC08579.jpg",
    width: 2560,
    height: 1786,
    blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoUAA4APxFysFAsJqSisAgBgCIJagCdABssn56ct5QJ8dAAAP7DZ4LfSqX7c+BAC26MFojNu5cei5q55hZChSrlTY2GymHop7z6lkF1dfrMLCNmYmTcSFJPzqUloW4iRfUwhpy6qgAAAA==",
  },
  "rg1_DSC08588": {
    src: "/media/rg1_DSC08588.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQBACdASoUAA0APxFysFAsJqSisAgBgCIJZACdACPzi8LFqsjeN5mbwAD8hxX8ylNSKp1EHIyYu/jrrKDeB/imlkcP+uMGbRYSWosDv1z6YHc21+dhNyMlN1FQ9fDDUJYUZ5HJDHfVBzW5DvOwpNvd9gA=",
  },
  "rg1_DSC08601": {
    src: "/media/rg1_DSC08601.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoUAA0APxFysFAsJqSisAgBgCIJQBYdhHnC8Il6v9yyuA9YAAD5INkBPxIwLzPcA7/PD3P2Lg1/11nmhGnIR3xD4ZwOyQbRtMRmd3oLZ4VjTL1BpOHV9bLrLsf78P1jr6tJYywAAAA=",
  },
  "rg1_DSC08632": {
    src: "/media/rg1_DSC08632.jpg",
    width: 2560,
    height: 1437,
    blur: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwBACdASoUAAsAPxFysFAsJqSisAgBgCIJbACdL12gAbn/dgAEl1xLjsW+ZdVAAPn1Fo9AVsoORJ9iWh6UYN2TmUC6DInuB7KckF7yXL6qzblj6d5m+7fvvlFs/pf+d5ZxvwgmAAA=",
  },
  "rg2_Chambre_Enfants": {
    src: "/media/rg2_Chambre_Enfants.jpg",
    width: 2560,
    height: 1600,
    blur: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQAwCdASoUAA0APxFysFAsJqSisAgBgCIJYwC2yBRfhb++8++AAPx0kUnu8Vj4qBLnLUKZOa2iuyHHHZELwD8W2YTWQF3bOuQufp+KrWF30e4yA/cdXz1JoOrfN2OneLKmPAAA",
  },
  "rg2_Chambre_Parentale_": {
    src: "/media/rg2_Chambre_Parentale_.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAwCdASoUAA0APxFwsFAsJiSisAgBgCIJZQC/OBjZ/exeAO2QCAD+aB9WDdC2Oj1gh6hUY2JOxJFyRKXZc8VV/1mgWFsetY3swcYHvGslfxZeQFFhHjEqHaHDWpk6tn2EqWDdEnJHe4Il144AAA==",
  },
  "rg2_Cuisine_v2": {
    src: "/media/rg2_Cuisine_v2.jpg",
    width: 2560,
    height: 3012,
    blur: "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBQCdASoUABgAPxF+slSsKCQjKAqpgCIJZQDE2BEd4YP+ZhKgx+BVdgp8cBYnn9QAAP60iJDlz/hd/PJ4cgv3ya/GJKbMqatOExm/DTtwOlqXwv7rax65w9N+FhfOUHSqze66lN8eFzGbIcRhvjtCVpsmEbUxBL+T1SpP+MDHWHqVd7p39j6z4hcL8QIAAAA=",
  },
  "rg2_Ext_Cam_A1_Commerce_1": {
    src: "/media/rg2_Ext_Cam_A1_Commerce_1.jpg",
    width: 2560,
    height: 1600,
    blur: "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwAwCdASoUAA0APxFwsFAsJiSisAgBgCIJYwCw7BYEXQCAs0mwAADgMAkPT4q6D2l9e/EHpx5inEiJYzFQ7isKKO8XWGC7kRw3MWIKaxUejTHICS/99b9++q3Z5Sx2K5d2DMWEP2neHvSFnhjpv/QFJ1XmjQ/ZRbLN5GCQH4AAAA==",
  },
  "rg2_Ext_Cam_c1_jardin_1": {
    src: "/media/rg2_Ext_Cam_c1_jardin_1.jpg",
    width: 2560,
    height: 1623,
    blur: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBACdASoUAA0APxFwsFAsJiSisAgBgCIJQBOgBF8QTuSzsqhQHJAPWAAA9ijApd86nTk6aN6nGTSVZRlhaljJEY9589JiZm78+iHMrNzj9ClDIO/aSKN9YywzSkCy7ovZMxMUZjYeZMFyUyQofBju65jP1F2oKAAAAA==",
  },
  "rg2_SDB_V2": {
    src: "/media/rg2_SDB_V2.jpg",
    width: 2560,
    height: 3012,
    blur: "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADwBACdASoUABgAPxF6tVOsJ6UiqAqpgCIJZQDA3A9hVZ8ggn0EamIINupM59FWkAAA/fnJTqjM23YKQRcY3HcQ/RRCEdFqoAd0z2ty1xHsLXyZ6LEHTQ5HegYr0mbdZlXDpwPnJcveihY2tysZZjRyQNa+3XfBhY4o4Xj9O9wmI+573V8R1XTgoLF/gAAA",
  },
  "rg2_Sejour_v2": {
    src: "/media/rg2_Sejour_v2.jpg",
    width: 2560,
    height: 1536,
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQBACdASoUAAwAPxFysFAsJqSisAgBgCIJZwAAWqAOFRWzpMFRy8w1gAD+080HPq9asQXsaXZtsBoqFmvwmeaY/ZD3qNX+UQhJ3a4V0GAm8BmOgD2YBV2maHe2kgyAAAA=",
  },
  "rg2_TypeB_3": {
    src: "/media/rg2_TypeB_3.jpg",
    width: 2560,
    height: 1600,
    blur: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBACdASoUAA0APxFysFAsJqSisAgBgCIJYgCdMoACfXjbPT47cPxFJl8gAP5kX8uF4Rfg6jJU15kwN5g+Ps9YaZpgpi2QouxsXV87ToL6nCy+f58hgq2/CsD74g6OIAUwLqDpTYoIIrfSfCmRrP7pSP6Gp8aw1ox+o7/0QAA=",
  },
  "th_amaia": {
    src: "/media/th_amaia.jpg",
    width: 2068,
    height: 1167,
    blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAwCdASoUAAsAPxFysVCsJqSisAgBgCIJZgCsLwAAkzBKHU40QqAA/eLF58IWAuUZsabYgUfSnD80xuHyPt04F/9P8o23SxUIX+S9KFkfp6xv7apqACeWbvHQDSXPHFDv30b+pLkRm8lawAA=",
  },
  "th_assalam_tg": {
    src: "/media/th_assalam_tg.jpg",
    width: 2560,
    height: 1440,
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoUAAsAPxFysVCsJqSisAgBgCIJZQDA3CGWOTlOkVwRYw8QAP6ykVNUZvC9rw4ZfPwJ0Re7hwUtceIxhMGU8DHOAGvTakGoOE0RiBYZUVyUIUeaN4AliwAA",
  },
  "th_bougainvillier": {
    src: "/media/th_bougainvillier.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwAwCdASoUAA0APxFwsFAsJiSisAgBgCIJZQAu/8BLApsKR7IXAAD9+bbRiWvpzZEeX6WNRmd5G7WaMFnphUIT3yi5IUtMivNcrZe0ZFn1DHokDVgdPvEQyuLcZej20bRvBqItkwIIDy1NAa/A6gAA",
  },
  "th_dyar_al_bahia": {
    src: "/media/th_dyar_al_bahia.jpg",
    width: 1304,
    height: 904,
    blur: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAwCdASoUAA4APxFwsFAsJiSisAgBgCIJaACdIDZBOqiGgaweNADdTjny8sCGUXwdy4Zo7N+wgEa41088wqWKT4eEKvDCQzAxV2yMJd6yhrjlY8PRtnu9c8hoZJzCJZidlGAHKVZ5wAAA",
  },
  "th_izdihar": {
    src: "/media/th_izdihar.jpg",
    width: 2560,
    height: 1335,
    blur: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACQAwCdASoUAAoAPxFwsFAsJiSisAgBgCIJQBibAqsak5x+8R1AAN3WyVz1639TkmWyl7YC1JY9ZSTdG6sdw9gsM7B+ehcOH9QvbCbQgmGcbJzn10aoAA==",
  },
  "th_lots": {
    src: "/media/th_lots.jpg",
    width: 1274,
    height: 715,
    blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoUAAsAPxFysFAsJqSisAgBgCIJbACdIExC8nPIZR7pCwMAAP5RwChizREIs6C2VZurmXLfu1gkB7s5ZrFlNnBoSXALkU9nV0p5rlLOzZ8SnENFwom9w0llJQ+R76W788BFABhR9HOAAA==",
  },
  "th_maamora": {
    src: "/media/th_maamora.jpg",
    width: 514,
    height: 293,
    blur: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQAwCdASoUAAsAPxFysFAsJqSisAgBgCIJbACdACElE0w6cDc8poAA/lHAKGSxYmHm11QLCuV7uD68yZ/r/hgOFQPSjdIwWZbRhT2IBlyUoUxtt/U/HWCsKJ46Ee29dZdflIYHuiRH7L277IsxND1G8yNIo6ucAAA=",
  },
  "th_oceane": {
    src: "/media/th_oceane.jpg",
    width: 2560,
    height: 1584,
    blur: "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQAwCdASoUAAwAPxFysFAsJqSisAgBgCIJQBOgBFq+URHQLk8kX4gA+OTvudQo1f4a2+MxaoczuitUYuJndb9ouvlCD1cArIiinxjHL2Yn5Oib+QphwnCmyXe5m+0Hb5cQB3Sn08XrebvCZ+4tSZgMMQ28d1B0M3Fy4lgA",
  },
  "th_odyssee": {
    src: "/media/th_odyssee.jpg",
    width: 2560,
    height: 1620,
    blur: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJZQC7ABnhx6zHmxwR9ndgAP7G5fSM6BS7dUvpLI+vbCnq+COam+kdTPTA15c/oTUliU6tdF6e+NVF+DKKKbdbk600XMVZqp3ExPgA",
  },
  "th_odyssee_studios": {
    src: "/media/th_odyssee_studios.jpg",
    width: 1536,
    height: 1024,
    blur: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJYgCdICXCvc9l84gumeYAAP34kTZrZw85Mt17qv0720yaWJOPSBrUrpmGi96vXio2mBLQ4Mn5szrHCzgPXbgfFS1bvIFYwsN3ycMNc0JBxbzP3J4RcygzrDm0lyYIAAA=",
  },
  "tp_assafa": {
    src: "/media/tp_assafa.jpg",
    width: 2560,
    height: 1825,
    blur: "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACQBACdASoUAA4APxFysFAsJqSisAgBgCIJQA7gbgC3/wG0mO1/svHkgUQocqgA/f9nbkfw5Rqpxf9ZPhq+Lb2CmCsHR6zF6kA3I3c6mDotol2vfo9oHQDjZ1qknZzJ6tKYvIFovG0HyPX4NLXxvr8OeVQAAA==",
  },
  "tp_jasmin": {
    src: "/media/tp_jasmin.jpg",
    width: 2560,
    height: 1440,
    blur: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQBACdASoUAAsAPxFysFAsJqSisAgBgCIJQBWGUABd4Ybj1dMB52UJAADJbvDxJrsRU1Jp3xq0/UbGEk8Cg2Aplpk8KuXvnbqrYUziam4aBfQA",
  },
  "tp_jnane_souss": {
    src: "/media/tp_jnane_souss.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQAwCdASoUAA0APxFysFCsJqSisAgBgCIJQBYdgzW7YmKTBGqAAP6NN7y/FXDnuyN4ev0cXQ1dH+t3HoyCJ5pC0ieZ/PprVGy0qh3RQWLJewEEEzGaP3hF4kKvx8EgAAA=",
  },
  "tp_massylia": {
    src: "/media/tp_massylia.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwAwCdASoUAA0APxFysFAsJqSisAgBgCIJQBZwA+SIQ1X6HdffOAD8YkeDFmpA12X9sb+Gfj0G6/0aUTPuqxvJGgAmEOVgzmurO9DjMjW4I8usS3JO3+sBopkUXdBuKeVF40a8AAA=",
  },
  "tp_patio_verde": {
    src: "/media/tp_patio_verde.jpg",
    width: 2560,
    height: 1707,
    blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoUAA0APxFwsFAsJiSisAgBgCIJYwC7ABjbBh8aWHsSYoHgAP293As45SWdR1jpuKgB2eMrv1qYUeh1YX8/2xlqm6m3PoAoo+eWENN6yP73xcNvwY1DXDqP8qCnLV16Lao0o0PFjiW/LE34AAA=",
  },
  "yt_-HLsqhzvkZU": {
    src: "/media/yt_-HLsqhzvkZU.jpg",
    width: 1280,
    height: 720,
    blur: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQAwCdASoUAAsAPxFysFAsJqSisAgBgCIJZgC06Bud3dmmzrwAAPjVJyGO5ZBKA/vEFP9FWbOTCVMIhJ1yaOuvDwdp8z3/jte3hJuOtDUjg2kaHqqT5/EnX+Hy2XDmRzXXPPr/LDDL0+ED+38u/RH+6riIq/jZsXyQHHUAAAA=",
  },
  "yt_LNZ-H3M0mH0": {
    src: "/media/yt_LNZ-H3M0mH0.jpg",
    width: 1280,
    height: 720,
    blur: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAwCdASoUAAsAPxF0sFCsJqSisAgBgCIJQBOgBFOs1I1ZHKvJI+UAAP3jXrV1sp+ygH+F1S3rYah274m8XrCDsel1AKM7WwIgmUGy2JqvCe8lsUiHfzS8NSxEtO2Eq/AAAA==",
  },
  "yt_eRqSNZToeig": {
    src: "/media/yt_eRqSNZToeig.jpg",
    width: 1280,
    height: 720,
    blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwAwCdASoUAAsAPxFysVAsJqSisAgBgCIJagC7AA8g+fP++iAA/mnEPQokSXE3acMeZoa6Iu4GvdMoGNJhOBNLgaRndccAMviDW3NUURRDz3iFfLp7SX3cZjSurXf242V2lsKvVbp+XRvg86BC0wAAAAA=",
  },
} as const satisfies Record<string, MediaAsset>;

export type MediaKey = keyof typeof media;
